### PR TITLE
Fix test-vpn glitches on macOS.

### LINKED ISSUE #2746: curl: (6) Could not resolve host: kubernetes.default
## Describe the bug

This is a newly built kubernetes cluster:

```shell
➜  ~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}

➜  ~ telepresence version
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)

➜  ~ kubectl get all -n ambassador
NAME                                   READY   STATUS    RESTARTS   AGE
pod/traffic-manager-865bfcbc96-7b2v4   1/1     Running   0          20m

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
service/agent-injector    ClusterIP   10.100.89.35   <none>        443/TCP              20m
service/traffic-manager   ClusterIP   None           <none>        8081/TCP,15766/TCP   20m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/traffic-manager   1/1     1            1           20m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/traffic-manager-865bfcbc96   1         1         1       20m
```

I use ```telepresence connect ``` , but it doesn't work: 

```shell
➜  ~ telepresence loglevel debug
Connected to context kubernetes-admin@kubernetes (https://lb.jdkhome.com:6443)
➜  ~ telepresence quit -r -u   
Telepresence Network quitting...done
Telepresence Traffic Manager quitting...done
➜  ~ telepresence connect      
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/linkji/Library/Logs/telepresence '/Users/linkji/Library/Application Support/telepresence'
Password:
Launching Telepresence User Daemon
Connected to context kubernetes-admin@kubernetes (https://lb.jdkhome.com:6443)
➜  ~ telepresence status 
Root Daemon: Running
  Version   : v2.7.1 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 10.0.0.200/32
User Daemon: Running
  Version         : v2.7.1 (api 3)
  Executable      : /usr/local/bin/telepresence
  Install ID      : 0cf422d8-57f6-4760-bfba-3022882b91af
  Ambassador Cloud:
    Status    : Logged out
    User ID   : 
    Account ID: 
    Email     : 
  Status            : Connected
  Kubernetes server : https://lb.jdkhome.com:6443
  Kubernetes context: kubernetes-admin@kubernetes
  Intercepts        : 0 total
➜  ~ curl -ik https://kubernetes.default
curl: (6) Could not resolve host: kubernetes.default
➜  ~ telepresence gather-logs
Connected to context kubernetes-admin@kubernetes (https://lb.jdkhome.com:6443)
Telepresence Network disconnecting...done
Telepresence Traffic Manager disconnecting...done
Logs have been exported to /Users/linkji/telepresence_logs.zip
```

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9395810/telepresence_logs.zip)

## To Reproduce
see description above.

## Expected behavior

```shell
telepresence connect
curl -ik https://kubernetes.default
```
This command should return the correct content.

**Versions (please complete the following information):**

### Output of `telepresence version`

```shell
➜  ~ telepresence version
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)
```

### Operating system of workstation running `telepresence` commands

macOS Monterey v12.4 (m1)

###  Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

```shell
➜  ~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

## VPN-related bugs

```shell
➜  ~ telepresence test-vpn
Telepresence Network is already disconnected
Telepresence Traffic Manager is already disconnectedPlease disconnect from your VPN now and hit enter once you're disconnected...

Please connect to your VPN now and hit enter once you're connected...

Connected to context kubernetes-admin@kubernetes (https://lb.jdkhome.com:6443)

Telepresence Network disconnecting...done
Telepresence Traffic Manager disconnecting...done

---------- Test Results:
✅ pod subnet 10.0.0.0/24 is clear of VPN
✅ pod subnet 10.36.0.0/24 is clear of VPN
✅ pod subnet 10.44.0.0/24 is clear of VPN
✅ svc subnet 10.96.0.0/12 is clear of VPN

Still having issues? Please create a new github issue at https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md
 Please make sure to add the following to your issue:
 * Run `telepresence loglevel debug`, try to connect, then run `telepresence gather_logs`. It will produce a zipfile that you should attach to the issue.
 * Which VPN client are you using?
 * Which VPN server are you using?
 * How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf
```

## Additional context

In order to reproduce this problem, I specially built a new kubernetes cluster. 😂😂😂

### LINKED ISSUE #2900: Unable To Connect to Service Endpoints in cluster
**Describe the bug**

After running telepresence connect successfully, I am unable to successfully run a curl command against a service running within our kubernetes cluster. DNS resolves successfully to the right IP address but the request just hangs until it times out, so there appears to be something off with the routing of my local machine. 

```
 curl -v atlas-service.master:443                                                                                                                                      
*   Trying 172.20.84.209:443...
```

Its worth mentioning I am connected to a VPN but the `test-vpn` command comes up  green. 

```
Telepresence Daemons have already quit
Please disconnect from your VPN now and hit enter once you're disconnected...

Please connect to your VPN now and hit enter once you're connected...

Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context preview (https://7C3D28FDA041BEAD123092475E77A333.gr7.us-east-1.eks.amazonaws.com)

---------- Test Results:
✅ svc subnet 172.20.0.0/16 is clear of VPN
```

**Expected behavior**
I expect to receive a 400 bad request status code returned back

**Versions (please complete the following information):**
``` 
tp version                                                                                                                                                            
Client: v2.9.2 (api v3)
Root Daemon: v2.9.2 (api v3)
User Daemon: v2.9.2 (api v3)
Traffic Manager: v2.9.2
Enhanced client version v1.4.4

OS Info
System Software Overview:
  System Version: macOS 12.4 (21F79)
  Kernel Version: Darwin 21.5.0
  Boot Volume: Macintosh HD
  Secure Virtual Memory: Enabled
  System Integrity Protection: Enabled

 k version                                                                                                                                                             
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - perimeter81
 - Which VPN server are you using?
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

We're using perimeter 81 as our VPN

**Additional context**
Setting also-proxy setting to 172.20.0.0/16 doesn't do anything seemingly but creating a manual route locally to the tunnel created by telepresence does result in the traffic being routed as it should
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/10071790/telepresence_logs.zip)

### PR DESCRIPTION
**Pull request by thallgren**
## Description

Fix a couple of glitches in `telepresence test-vpn` that made routes with gateway links invisible and included routes with zero IP.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by knlambert — APPROVED** [review]

File: pkg/vif/routing/routing_darwin.go [hunk 1]
```diff
@@ -57,16 +57,16 @@ func GetRoutingTable(ctx context.Context) ([]*Route, error) {
...
-			if !ok {
-				continue
+			var gwIP net.IP
+			if gwAddr, ok := gw.(*route.Inet4Addr); ok {
+				gwIP = gwAddr.IP[:]
 			}
 			routes = append(routes, &Route{
 				Interface: iface,
-				Gateway:   net.IP(gw.IP[:]),
+				Gateway:   gwIP,
```
Comment (knlambert) [inline pkg/vif/routing/routing_darwin.go:66]: So this can now be nil ? What does that mean in this context, just curious.

Comment (thallgren) [reply pkg/vif/routing/routing_darwin.go:66]: It means that the gateway is of type link (to another interface), so there's no gateway IP. E.g. a VPN uses an interface and then also manages other subnets.
