### PR TITLE
Let the Helm chart hooks include the helm revision as a query parameter.

### LINKED ISSUE #2954: intercept error with request timed out while waiting for agent
when i run `telepresence intercept erda-cluster-manager -n erda -p 8280:80 -p 8294:9094 -p 8295:9095 --env-file .vscode/go-debug.env` try to intercept pods traffic, [telepresence](https://github.com/telepresenceio/telepresence) report error with `telepresence intercept: error: request timed out while waiting for agent erda-cluster-manager.erda to arrive`.

the version of telepresence is v2.9.5, server system version is ubuntu 18.04, client system is archlinux latest(just sync), kubernetes verison is 1.20.1

here the log
connector.log
```
2022-12-27 14:23:21.5011 info    Telepresence Connector v2.9.5 (api v3) starting...
2022-12-27 14:23:21.5011 info    PID is 73783
2022-12-27 14:23:21.5012 info    
2022-12-27 14:23:21.5043 info    connector/server-grpc : gRPC server started
2022-12-27 14:23:21.6689 info    connector/session : -- Starting new session
2022-12-27 14:23:21.6691 info    connector/session : Connecting to k8s cluster...
2022-12-27 14:23:21.6955 info    connector/session : Server version v1.20.0
2022-12-27 14:23:21.6957 info    connector/session : Context: kubernetes-admin@kubernetes
2022-12-27 14:23:21.6958 info    connector/session : Server: https://192.168.1.132:6443
2022-12-27 14:23:21.6962 info    connector/session : Connected to context kubernetes-admin@kubernetes (https://192.168.1.132:6443)
2022-12-27 14:23:21.7007 info    connector/session : Connecting to traffic manager...
2022-12-27 14:23:21.8471 info    connector/session : Connected to traffic-manager 2.9.5
2022-12-27 14:23:21.8564 info    connector/session : Connecting to root daemon...
2022-12-27 14:23:24.6941 info    connector/session : Configuration reloaded
```
trafix-manager-xxxx.log
```
2022-12-27 04:11:16.9962 info    Traffic Manager v2.9.5 [uid:1000,gid:0]
2022-12-27 04:11:16.9979 info    unable to load license: error reading license: open /home/telepresence/license: no such file or directory
2022-12-27 04:11:16.9983 info    starting cloud token watchers
2022-12-27 04:11:22.0199 info    Using cluster domain "cluster.local."
2022-12-27 04:11:22.0267 info    Extracting service subnet 10.96.0.0/12 from create service error message
2022-12-27 04:11:22.0268 info    Using podCIDRStrategy: auto
2022-12-27 04:11:22.0268 info    Using AlsoProxy: []
2022-12-27 04:11:22.0268 info    Using NeverProxy: []
2022-12-27 04:11:22.0268 info    ExcludeSuffixes: [.com .io .net .org .ru]
2022-12-27 04:11:22.0269 info    IncludeSuffixes: []
2022-12-27 04:11:22.1284 info    Scanning 4 nodes
2022-12-27 04:11:22.1287 info    Found 4 subnets
2022-12-27 04:11:22.1288 info    Deriving subnets from podCIRs of nodes
2022-12-27 04:11:23.2881 info    Using traffic-agent image "docker.io/datawire/ambassador-telepresence-agent:1.13.5"
2022-12-27 04:11:23.3425 info    prometheus : Prometheus metrics server not started
2022-12-27 04:11:23.3426 info    agent-injector : Loading ConfigMaps from []
2022-12-27 04:11:23.3428 info    agent-injector : Mutating webhook service is listening on :443
2022-12-27 04:11:23.3427 info    cli-config : Started watcher for ConfigMap traffic-manager-clients
2022-12-27 04:11:24.3431 info    agent-configs : Started watcher for Services cluster wide
2022-12-27 04:11:24.3432 info    agent-configs : Started watcher for ConfigMap telepresence-agents cluster wide
2022-12-27 04:11:24.3915 info    agent-configs : Successfully rolled out erda-cluster-manager.erda
2022-12-27 04:11:26.5848 info    agent-injector/conn=10.244.2.126:443 : Injecting traffic-agent into pod erda-cluster-manager-57868cbb5-.erda
2022-12-27 04:11:26.5879 info    agent-injector/conn=10.244.2.126:443 : Injecting 7 patches into pod erda-cluster-manager-57868cbb5-.erda
2022-12-27 04:13:14.1054 info    agent-configs : Ended watcher for Services cluster wide
2022-12-27 04:13:14.1054 info    agent-configs : Ended watcher for ConfigMap telepresence-agents cluster wide
2022-12-27 04:13:14.1384 info    agent-injector/conn=10.244.2.126:443 : Successfully rolled out erda-cluster-manager.erda
2022-12-27 04:20:12.7514 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "tel2-recursion-check.kube-system.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:40:07.0919 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:40:07.0950 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:40:07.5697 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:40:07.5732 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:12.7841 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:12.8959 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:12.9940 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:12.9970 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:18.7723 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:43:18.7724 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "metadata.google.internal." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 05:51:52.5856 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "tel2-recursion-check.kube-system.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 06:03:42.8814 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 06:03:43.7878 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 06:03:44.0535 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
2022-12-27 06:03:44.0538 error   httpd/conn=127.0.0.1:8081 : LookupIP failed, trying LookupIP "archlinux-br.com.br.airdream." : session_id="457f6708-8e73-4263-972e-32b2965e1b6f"
```

daemon.log
```
2022-12-27 14:23:21.2779 info    ---
2022-12-27 14:23:21.2780 info    Telepresence daemon v2.9.5 (api v3) starting...
2022-12-27 14:23:21.2781 info    PID is 73767
2022-12-27 14:23:21.2781 info    
2022-12-27 14:23:21.2806 info    daemon/server-grpc : gRPC server started
2022-12-27 14:23:21.8606 info    daemon/session : -- Starting new session
2022-12-27 14:23:21.8677 info    daemon/session : Connected to Manager 2.9.5
2022-12-27 14:23:21.9055 info    daemon/session : also-proxy subnets []
2022-12-27 14:23:21.9057 info    daemon/session : never-proxy subnets [192.168.1.132/32]
2022-12-27 14:23:21.9059 info    daemon/session : Configuration reloaded
2022-12-27 14:23:22.4150 info    daemon/session : Starting Endpoint
2022-12-27 14:23:22.4153 info    daemon/session/watch-cluster-info : Setting cluster DNS to 10.244.2.126
2022-12-27 14:23:22.4154 info    daemon/session/watch-cluster-info : Setting cluster domain to "cluster.local."
2022-12-27 14:23:22.4154 info    daemon/session/watch-cluster-info : also-proxy subnets []
2022-12-27 14:23:22.4155 info    daemon/session/watch-cluster-info : never-proxy subnets [192.168.1.132/32]
2022-12-27 14:23:22.4155 info    daemon/session/watch-cluster-info : Adding Service subnet 10.96.0.0/12
2022-12-27 14:23:22.4156 info    daemon/session/watch-cluster-info : Adding pod subnet 10.244.0.0/24
2022-12-27 14:23:22.4156 info    daemon/session/watch-cluster-info : Adding pod subnet 10.244.1.0/24
2022-12-27 14:23:22.4156 info    daemon/session/watch-cluster-info : Adding pod subnet 10.244.2.0/24
2022-12-27 14:23:22.4157 info    daemon/session/watch-cluster-info : Adding pod subnet 10.244.3.0/24
2022-12-27 14:23:22.4172 info    daemon/session/watch-cluster-info : started command ["ip" "a" "add" "10.96.0.0/12" "dev" "tel0"] : dexec.pid="73838"
2022-12-27 14:23:22.4187 info    daemon/session/watch-cluster-info :  : dexec.pid="73838" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.4245 info    daemon/session/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="73838"
2022-12-27 14:23:22.4277 info    daemon/session/watch-cluster-info : started command ["ip" "a" "add" "10.244.0.0/24" "dev" "tel0"] : dexec.pid="73840"
2022-12-27 14:23:22.4278 info    daemon/session/watch-cluster-info :  : dexec.pid="73840" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.4307 info    daemon/session/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="73840"
2022-12-27 14:23:22.4320 info    daemon/session/watch-cluster-info : started command ["ip" "a" "add" "10.244.1.0/24" "dev" "tel0"] : dexec.pid="73841"
2022-12-27 14:23:22.4322 info    daemon/session/watch-cluster-info :  : dexec.pid="73841" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.4370 info    daemon/session/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="73841"
2022-12-27 14:23:22.4384 info    daemon/session/watch-cluster-info : started command ["ip" "a" "add" "10.244.2.0/24" "dev" "tel0"] : dexec.pid="73843"
2022-12-27 14:23:22.4385 info    daemon/session/watch-cluster-info :  : dexec.pid="73843" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.4435 info    daemon/session/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="73843"
2022-12-27 14:23:22.4448 info    daemon/session/watch-cluster-info : started command ["ip" "a" "add" "10.244.3.0/24" "dev" "tel0"] : dexec.pid="73846"
2022-12-27 14:23:22.4453 info    daemon/session/watch-cluster-info :  : dexec.pid="73846" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.4510 info    daemon/session/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="73846"
2022-12-27 14:23:22.4567 info    daemon/session/dns/resolved : started command ["docker" "inspect" "bridge" "-f" "{{(index .IPAM.Config 0).Gateway}}"] : dexec.pid="73849"
2022-12-27 14:23:22.4570 info    daemon/session/dns/resolved :  : dexec.pid="73849" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:22.5370 info    daemon/session/dns/resolved :  : dexec.pid="73849" dexec.stream="stdout" dexec.data="172.17.0.1\n"
2022-12-27 14:23:22.5472 info    daemon/session/dns/resolved : finished successfully: exit status 0 : dexec.pid="73849"
2022-12-27 14:23:22.5511 info    daemon/session/dns/resolved : listening to docker bridge at 172.17.0.1
2022-12-27 14:23:22.5515 info    daemon/session/dns/resolved/Server : Configuring DNS IP 10.244.2.126
2022-12-27 14:23:24.5631 error   daemon/session/dns/resolved/SanityCheck : resolver did not receive requests from systemd-resolved
2022-12-27 14:23:24.5634 error   daemon/session/dns/resolved/SanityCheck : goroutine "/daemon/session/dns/resolved/SanityCheck" exited with error: resolved not configured
2022-12-27 14:23:24.5635 info    daemon/session/dns/resolved/Server:shutdown_logger : shutting down (gracefully)...
2022-12-27 14:23:24.5638 info    daemon/session/dns/resolved:shutdown_logger : shutting down (gracefully)...
2022-12-27 14:23:24.5698 info    daemon/session/dns/resolved:shutdown_status :   final goroutine statuses:
2022-12-27 14:23:24.5700 info    daemon/session/dns/resolved:shutdown_status :     /daemon/session/dns/resolved/SanityCheck: exited with error
2022-12-27 14:23:24.5700 info    daemon/session/dns/resolved:shutdown_status :     /daemon/session/dns/resolved/Server     : exited without error
2022-12-27 14:23:24.5701 info    daemon/session/dns : Unable to use systemd-resolved, falling back to local server
2022-12-27 14:23:24.5702 info    daemon/session/dns/legacy : Automatically set -dns=202.106.0.20
2022-12-27 14:23:24.5721 info    daemon/session/dns/legacy : started command ["docker" "inspect" "bridge" "-f" "{{(index .IPAM.Config 0).Gateway}}"] : dexec.pid="73951"
2022-12-27 14:23:24.5725 info    daemon/session/dns/legacy :  : dexec.pid="73951" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.6566 info    daemon/session/dns/legacy :  : dexec.pid="73951" dexec.stream="stdout" dexec.data="172.17.0.1\n"
2022-12-27 14:23:24.6667 info    daemon/session/dns/legacy : finished successfully: exit status 0 : dexec.pid="73951"
2022-12-27 14:23:24.6692 info    daemon/session/dns/legacy : listening to docker bridge at 172.17.0.1
2022-12-27 14:23:24.6735 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-D" "OUTPUT" "-j" "TELEPRESENCE_DNS"] : dexec.pid="73963"
2022-12-27 14:23:24.6737 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73963" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.6770 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73963" dexec.stream="stdout+stderr" dexec.data="iptables v1.8.8 (legacy): Couldn't load target `TELEPRESENCE_DNS':No such file or directory\n"
2022-12-27 14:23:24.6771 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73963" dexec.stream="stdout+stderr" dexec.data="\n"
2022-12-27 14:23:24.6772 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73963" dexec.stream="stdout+stderr" dexec.data="Try `iptables -h' or 'iptables --help' for more information.\n"
2022-12-27 14:23:24.6777 info    daemon/session/dns/legacy/NAT-redirect : finished with error: exit status 2 : dexec.pid="73963"
2022-12-27 14:23:24.6789 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-F" "TELEPRESENCE_DNS"] : dexec.pid="73964"
2022-12-27 14:23:24.6792 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73964" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.6819 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73964" dexec.stream="stdout+stderr" dexec.data="iptables: No chain/target/match by that name.\n"
2022-12-27 14:23:24.6826 info    daemon/session/dns/legacy/NAT-redirect : finished with error: exit status 1 : dexec.pid="73964"
2022-12-27 14:23:24.6838 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-X" "TELEPRESENCE_DNS"] : dexec.pid="73965"
2022-12-27 14:23:24.6840 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73965" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.6874 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73965" dexec.stream="stdout+stderr" dexec.data="iptables: No chain/target/match by that name.\n"
2022-12-27 14:23:24.6882 info    daemon/session/dns/legacy/NAT-redirect : finished with error: exit status 1 : dexec.pid="73965"
2022-12-27 14:23:24.6895 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-N" "TELEPRESENCE_DNS"] : dexec.pid="73966"
2022-12-27 14:23:24.6898 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73966" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.6941 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73966"
2022-12-27 14:23:24.6953 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "57501" "-j" "RETURN"] : dexec.pid="73967"
2022-12-27 14:23:24.6957 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73967" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7019 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73967"
2022-12-27 14:23:24.7034 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "47425" "-j" "RETURN"] : dexec.pid="73968"
2022-12-27 14:23:24.7037 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73968" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7095 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73968"
2022-12-27 14:23:24.7108 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "37294" "-j" "RETURN"] : dexec.pid="73970"
2022-12-27 14:23:24.7109 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73970" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7167 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73970"
2022-12-27 14:23:24.7180 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "46785" "-j" "RETURN"] : dexec.pid="73972"
2022-12-27 14:23:24.7183 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73972" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7236 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73972"
2022-12-27 14:23:24.7250 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "45109" "-j" "RETURN"] : dexec.pid="73973"
2022-12-27 14:23:24.7254 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73973" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7305 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73973"
2022-12-27 14:23:24.7319 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "36964" "-j" "RETURN"] : dexec.pid="73974"
2022-12-27 14:23:24.7322 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73974" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7376 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73974"
2022-12-27 14:23:24.7391 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "36578" "-j" "RETURN"] : dexec.pid="73975"
2022-12-27 14:23:24.7393 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73975" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7447 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73975"
2022-12-27 14:23:24.7460 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "37161" "-j" "RETURN"] : dexec.pid="73976"
2022-12-27 14:23:24.7461 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73976" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7516 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73976"
2022-12-27 14:23:24.7530 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "40481" "-j" "RETURN"] : dexec.pid="73977"
2022-12-27 14:23:24.7531 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73977" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7585 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73977"
2022-12-27 14:23:24.7597 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--source" "192.168.1.130" "--sport" "48291" "-j" "RETURN"] : dexec.pid="73978"
2022-12-27 14:23:24.7599 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73978" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7652 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73978"
2022-12-27 14:23:24.7665 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-A" "TELEPRESENCE_DNS" "-p" "udp" "--dest" "202.106.0.20/32" "--dport" "53" "-j" "DNAT" "--to-destination" "127.0.0.1:35635"] : dexec.pid="73979"
2022-12-27 14:23:24.7666 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73979" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7723 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73979"
2022-12-27 14:23:24.7735 info    daemon/session/dns/legacy/NAT-redirect : started command ["iptables" "-t" "nat" "-I" "OUTPUT" "1" "-j" "TELEPRESENCE_DNS"] : dexec.pid="73980"
2022-12-27 14:23:24.7737 info    daemon/session/dns/legacy/NAT-redirect :  : dexec.pid="73980" dexec.stream="stdin" dexec.err="EOF"
2022-12-27 14:23:24.7781 info    daemon/session/dns/legacy/NAT-redirect : finished successfully: exit status 0 : dexec.pid="73980"

```

### PR DESCRIPTION
**Pull request by thallgren**
## Description

A race condition may occur during upgrade where the http call issued from a job started by a Helm pre-delete hook, is served by the upgraded traffic-manager rather than the deleted one.

This commit adds the `Helm.Revision` as a `HELM_REVISION` environment variable to the traffic-manager, and as a query parameter to the URL calls that the Helm hooks perform. The service then compares those revisions and discards the call when they don't match.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

File: cmd/traffic/cmd/manager/internal/mutator/service.go [hunk 1]
```diff
@@ -90,7 +93,15 @@ func ServeMutator(ctx context.Context) error {
 	})
 	mux.HandleFunc("/uninstall", func(w http.ResponseWriter, r *http.Request) {
 		ctx := r.Context()
-		dlog.Debug(ctx, "Received uninstall request...")
+		dlog.Info(ctx, "Received uninstall request...")
+		q := r.URL.Query()
+		if rev, err := strconv.Atoi(q.Get("revision")); err != nil || rev != env.HelmRevision {
+			dlog.Warn(ctx, "uninstall request discarded. Helm revisions don't match")
```
Comment (josecv) [inline cmd/traffic/cmd/manager/internal/mutator/service.go]: could we include the requested and current revision in this log line? we should directly include the result of `q.Get("revision")` just in case it didn't parse successfully (which seems unlikely given where it's coming from, but still)

**Review by josecv — APPROVED** [review]
one point about logging, otherwise lgtm
