### PR TITLE
Fix Windows DNS issues

### LINKED ISSUE #2939: dns resolution on windows always requires suffix even with active intercept
**Describe the bug**
services can only be reached using dns suffix and not the short name.

**To Reproduce**
PS C:\WINDOWS> telepresence loglevel debug
PS C:\WINDOWS> telepresence intercept local-deployment --namespace thx --local-only
PS C:\WINDOWS> curl http://ujm:8000
curl : The remote name could not be resolved: 'ujm'
At line:1 char:1
+ curl http://ujm:8000
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExcept
   ion
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\WINDOWS> telepresence gather-logs --output-file [telepresence_logs.zip](url)
**Expected behavior**
be able to connect to the service using the shortname (without dns suffix)

**Versions (please complete the following information):**
 - Output of `telepresence version`
 PS C:\WINDOWS> telepresence version
Enhanced Client: v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
Traffic Manager: v2.9.5
 - Operating system of workstation running `telepresence` commands
 windows 10
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - gke autopilot 1.24PS C:\WINDOWS> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5-gke.600", GitCommit:"fb4964ee848bc4d25d42d60386c731836059d1d8", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:55Z", GoVersion:"go1.18.6b7", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
short names also don't work with global intercepts. 
short names work on wsl2 when using local only or global intercepts

### PR DESCRIPTION
**Pull request by thallgren**
## Description

This PR contains two major changes for Windows.

1. The communication between the CLI and the daemons no longer use named pipes. Instead, they use a unix socket, just like we do on other platforms. The named pipes caused the daemons to sometimes hang during shutdown.
2. The DNS search path is now assigned both to Telepresence VIF and globally, since just assigning it to the VIF didn't "take" on some platforms (most notably Windows Server).

The PR also contains some fixes in the integration tests that removes panics.

I recommend reviewing this PR one commit at a time.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

File: pkg/vif/device_windows.go [hunk 1]
```diff
@@ -130,46 +143,103 @@ func (t *nativeDevice) setDNS(ctx context.Context, server net.IP, domains []stri
 			_ = luid.FlushDNS(oldFamily)
 		}
 	}
-	if err = luid.SetDNS(family, []netip.Addr{addrFromIP(server)}, domains); err != nil {
+	serverStr := server.String()
```
Comment (knlambert) [inline pkg/vif/device_windows.go:146]: Do we use this `winipcfg` package which seems to be a VPN client to manipulate the DNS ? Is it just because it has some useful functions ?

**Review by knlambert — APPROVED** [review]

File: pkg/vif/device_windows.go (hunk 1 above)
Comment (thallgren) [reply pkg/vif/device_windows.go:146]: Yes, winipcfg is also used by the wireguard VPN, as is the Wireguard TUN device that we also use (the one that binds to wintun.dll). So in essence, we mimic parts of the Wireguard VPN for our routing and DNS.
