### PR TITLE
Don't panic when --docker-run is combined with --name

### LINKED ISSUE #2953: Panic if --docker-run --name uses space not '=' to separate option name from value
**Describe the bug**

Just migrating from legacy telepresence and dropping in telepresence 2  with existing use of
legacy telepresence panicked. 

Stack trace led me to the 

`startInDocker` function in the 

https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/cli/intercept/state.go

file.

Specifically the attempt to extract the value of the '--name' option:

`name, hasName := getArg("--name")`

fails and panics in the `getArg` function:

 ```go
if i+1 < len(args) {
					return parts[i+1], true
```
As it is assumed the `parts` array has enough elements, which is not the case if the `--name` option is of the form

`--name the-name`

rather than:

`--name=the-name`

as the string is only split on '=':

```go
   parts := strings.Split(arg, "=")
```

**To Reproduce**

run telepresence v2 using legacy options and in the --docker-run arguments specify `--name the-name` not `--name=the-name`

```sh
telepresence --swap-deployment deployment-name --namespace blah --docker-run --name the-name ...
```

**Expected behavior**
telepresence to not panic and to run the docker container as specified

**Versions (please complete the following information):**
 -  all v2.9.5
 - Linux Alma 8
 - Rancher k3s

### PR DESCRIPTION
**Pull request by thallgren**
## Description

The code that parses arguments after `--` would panic on flags that
used `--flag value` instead of `--flag=value`. This commit ensures that
both variants work.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

File: pkg/client/cli/intercept/state.go [hunk 1]
```diff
@@ -329,34 +329,43 @@ func (s *state) CreateRequest(ctx context.Context) (*connector.CreateInterceptRe
 	return ir, nil
 }
 
+func getArg(args []string, flag string) (string, error) {
```
Comment (josecv) [inline pkg/client/cli/intercept/state.go]: maybe this should be called `getArgForDocker`?

File: pkg/client/cli/intercept/state.go [hunk 2]
```diff
@@ -329,34 +329,43 @@ func (s *state) CreateRequest(ctx context.Context) (*connector.CreateInterceptRe
...
+				}
+			}
+		case strings.HasPrefix(arg, feq):
+			v = arg[len(feq):]
+		default:
+			continue
+		}
+		if v == "" {
+			return "", errors.New("docker flag `--name` requires a value")
+		}
```
Comment (josecv) [inline pkg/client/cli/intercept/state.go]: This shouldn't be `--name`, but should rather include the provided `flag`

**Review by josecv — CHANGES_REQUESTED** [review]

File: pkg/client/cli/intercept/state.go (hunk 2 above)
Comment (thallgren) [reply pkg/client/cli/intercept/state.go]: Haha, yeah :-)

**Review by josecv — APPROVED** [review]
