### PR TITLE
IPv6 enable the telepresence docker network.

### LINKED ISSUE #3179: Enable IPv6 on the telepresence docker network
An apache running in a docker based intercept handler might fail with a DNS lookup failure when it dials other services in the cluster even though the DNS is resolved and returned. The reason appears to be that IPv6 isn't enabled, because when adding a network where it is, that resolves the problem.

The solution is to add IPv6 to the `telepresence` network, but doing that isn't straightforward because it requires that IPv6 has been enabled in `/etc/docker/daemon.json`, or that the network is created with an explicitly added IPv6 subnet and gateway. Let's say we create the `telepresence` network using `--ipv6` . If it fails, I can see the following options:
1. inform the user that ipv6 must be added to `/etc/docker/daemon.json`
2. make another attempt without `--ipv6`, and log a warning that some DNS functionality might not be available.
3. make another attempt, but add an explicit subnet/gateway using `--subnet` and `--gateway` flag.

Number 3 is probably the most user-friendly, but it also requires Telepresence to select a random subnet, which defeats the purpose of defining this in `/etc/docker/daemon.json`.

### PR DESCRIPTION
**Pull request by thallgren**
## Description

DNS AAAA queries will never reach a Telepresence daemon that runs in a Docker container unless that container is attached to an IPv6 enabled network. This commit therefore ensures that the "telepresence" network is IPv6 enabled by first trying to create it that way, and if that fails due to the lack of an IPv6 pool in `/etc/docker/daemon.json`, by adding a random IPv6 subnet and gateway to force the enablement without the existence of such a pool.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

File: pkg/client/docker/network.go [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+	ipam := &resource.IPAM
+
+	// Save original Config to use a source for copy
+	numConfigs := len(ipam.Config)
+	ipamConfig := make([]network.IPAMConfig, numConfigs)
+	copy(ipamConfig, ipam.Config)
+
+	// Make attempts to add a random IPv6 subnet and gateway to IPAM
+	for retry := 0; retry < 5; retry++ {
+		ipn := fmt.Sprintf("%016x", rand.Int63())
```
Comment (knlambert) [inline pkg/client/docker/network.go:95]: I guess the probability of a conflict is super low. Would it generate an error ? Otherwise LGTM.

**Review by knlambert — APPROVED** [review]

File: pkg/client/docker/network.go (hunk 1 above)
Comment (thallgren) [reply pkg/client/docker/network.go:95]: The last attempt will be reported as an error if it gets to that.
