### PR TITLE
Fix SIGSEGV in tunnel.readLoop.

### LINKED ISSUE #2963: Daemon segfault
**Describe the bug**

My intercept stopped working without anything obvious popping up. When I was trying to restart the intercept I got this:

```
telepresence intercept: error: connection error: desc = "transport: error while dialing: dial unix /var/run/telepresence-daemon.socket: connect: connection refused" (socket rm failed with remove /var/run/telepresence-daemon.socket: permission denied); this usually means that the process has terminated ungracefully
```

This is the dump from the daemon log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17dfa3b]

goroutine 66993 [running]:
github.com/telepresenceio/telepresence/v2/pkg/tunnel.readLoop({0x2629b68, 0xc000b31e30}, {0x262f648, 0xc000858e70})
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:294 +0x3db
github.com/telepresenceio/telepresence/v2/pkg/tunnel.(*dialer).streamToConnLoop(0x0?, {0x2629b68?, 0xc000b31e30?}, 0x0?)
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:239 +0x6e
created by github.com/telepresenceio/telepresence/v2/pkg/tunnel.(*dialer).Start.func1
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:143 +0xaaf
```

**Versions (please complete the following information):**

```
$ telepresence version
Client         : v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
```

### PR DESCRIPTION
**Pull request by thallgren**
## Description

The `channelStream.Receive` incorrectly returned `nil, nil` when the
context was cancelled, causing a panic in the reader that expects
a mandatory message when the error is `nil`. This commit ensures that
the context error is returned and handled appropriately.

This PR also fixes a number of instability issues in our integration tests.

Closes https://github.com/telepresenceio/telepresence/issues/2963

## Checklist

 - [x] I made sure to update `./CHANGELOG.yml`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

File: pkg/client/cli/cloud/message.go [hunk 1]
```diff
@@ -31,18 +32,18 @@ type messageCache struct {
 }
 
 // newMessageCache returns a new messageCache, initialized from the users' if it exists.
-func newMessageCache(ctx context.Context) (*messageCache, error) {
+func newMessageCache(ctx context.Context) *messageCache {
```
Comment (knlambert) [inline pkg/client/cli/cloud/message.go:35]: I had no idea this thing existed, I would have thought it was in pro. I guess this change mitigates the issue.

**Review by knlambert — APPROVED** [review]
