### PR TITLE
Ensure that the docker container name is valid.

### LINKED ISSUE #14: launch of daemon container failed
When I try to connect to a cluster, I get this error:

```
launch of daemon container failed: docker: Error response from daemon: Invalid container name (tp-nick.santos@docker.com@nassau.us-east-1.eksctl.io), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed. See 'docker run --help'.
```

Looks like it's trying to generate a container name based on the cluster context, but that won't work because they have different allowed characters?

### PR DESCRIPTION
**Pull request by thallgren**
## Description

The name used for `docker run --name <name>` must comply with the
regular expression `[a-zA-Z0-9][a-zA-Z0-9_.-]`. This is however not true
for the name of a Kubernetes context. So when using a context name as
the argument to `--name`, it must be mangled so that any illegal
characters are replaced.

This commit adds the `SafeContainerName` function which replaces all
illegal characters with an underscore unless it's the very first
character, in which case it is replaced with an 'a'.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [x] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by jacoblbeck — DISMISSED** [review]

File: pkg/client/docker/daemon.go [hunk 1]
```diff
@@ -100,11 +100,32 @@ func DaemonOptions(ctx context.Context, name string) ([]string, *net.TCPAddr, er
...
+	}
+	return n.String()
+}
+
 // DaemonArgs returns the arguments to pass to a docker run when starting a container daemon.
 func DaemonArgs(name string, port int) []string {
 	return []string{
 		"connector-foreground",
-		"--name", "docker-" + name,
+		"--name", SafeContainerName("docker-" + name),
```
Comment (knlambert) [inline pkg/client/docker/daemon.go:128]: Is it the right place ? If I understand correctly, this is the name for the connector foreground, but we still have to use that saveContainerName function with the container name right ? `tp-something`

Comment (knlambert) [reply pkg/client/docker/daemon.go:128]: In `DaemonOptions`

Comment (thallgren) [reply pkg/client/docker/daemon.go:128]: Yes, I saw that too. It's added now.

**Review by jacoblbeck — APPROVED** [review]
